In [1]:
import torch
from torch.nn.utils.rnn import pad_packed_sequence, pack_padded_sequence, pad_sequence
from models.networks import CNNEmbedding
from models.utils import packCharsWithMask

In [2]:
s1 = [
    [1, 2, 3],
    [4, 3],
    [5, 2, 2, 3],
]

s2 = [
    [4, 3, 1, 6, 2],
    [1, 2, 3],
]

NUM_CHARS = 7
EMBEDDING_DIM = 3
    
model = CNNEmbedding(NUM_CHARS, EMBEDDING_DIM)

x, mask = packCharsWithMask([s1, s2])

print("Input (Packed)")
print(x.data.numpy())

print("\nMask")
print(((mask.numpy() == -1e9) * 1)[...,0])

with torch.no_grad():
    y = model(x, mask)
    
print("\nOutput (Packed)")
print(y.data.numpy())

print("\nOutput (Padded)")
r, lengths = pad_packed_sequence(y)
print(r.permute(1, 0, 2).numpy())

Input (Packed)
[[1 2 3 0 0]
 [4 3 1 6 2]
 [4 3 0 0 0]
 [1 2 3 0 0]
 [5 2 2 3 0]]

Mask
[[0 0 0 1 1]
 [0 0 0 0 0]
 [0 0 1 1 1]
 [0 0 0 1 1]
 [0 0 0 0 1]]

Output (Packed)
[[ 0.8804787  -0.12565537  1.0057945 ]
 [ 0.5860801   0.36556995  0.63799185]
 [ 0.21783246 -0.20901467  0.31337976]
 [ 0.8804787  -0.12565537  1.0057945 ]
 [ 0.5940787   0.1700411   0.8562769 ]]

Output (Padded)
[[[ 0.8804787  -0.12565537  1.0057945 ]
  [ 0.21783246 -0.20901467  0.31337976]
  [ 0.5940787   0.1700411   0.8562769 ]]

 [[ 0.5860801   0.36556995  0.63799185]
  [ 0.8804787  -0.12565537  1.0057945 ]
  [ 0.          0.          0.        ]]]
