In [1]:
import torch
from models.networks import CNNEmbedding
from models.utils import packCharsWithMask

In [2]:
s1 = [
    [1, 2, 3],
    [4, 3],
    [5, 2, 2, 3],
]

s2 = [
    [1, 2, 3],
    [4, 3, 1, 6, 2],
]

NUM_CHARS = 7
EMBEDDING_DIM = 3
    
model = CNNEmbedding(NUM_CHARS, EMBEDDING_DIM)

x, mask = packCharsWithMask([s1, s2])
print("Input")
print(x.data.numpy())

with torch.no_grad():
    y = model(x, mask)
    
print("\nOutput")
print(y.data.numpy())

Input
[[1 2 3 0 0]
 [4 3 0 0 0]
 [1 2 3 0 0]
 [4 3 1 6 2]]

Output
[[ 0.37057504  0.6678283   0.7527622 ]
 [-0.3555143   0.10169128  0.437469  ]
 [ 0.37057504  0.6678283   0.7527622 ]
 [ 0.04258546  0.49077216  0.6276345 ]]
